package com.exclamationlabs.connid.base.connector.configuration;

public enum ConnectorProperty {

    CONNECTOR_BASE_CONFIGURATION_ACTIVE,

    // Direct access token stored in configuration, no other auth
    CONNECTOR_BASE_AUTH_DIRECT_TOKEN,

    // JKS private key loading
    CONNECTOR_BASE_AUTH_JKS_ALIAS,
    CONNECTOR_BASE_AUTH_JKS_FILE,
    CONNECTOR_BASE_AUTH_JKS_PASSWORD,

    // JWT authentication
    CONNECTOR_BASE_AUTH_JWT_AUDIENCE,
    CONNECTOR_BASE_AUTH_JWT_EXPIRATION_PERIOD,
    CONNECTOR_BASE_AUTH_JWT_ISSUER,
    CONNECTOR_BASE_AUTH_JWT_SECRET,
    CONNECTOR_BASE_AUTH_JWT_SUBJECT,
    CONNECTOR_BASE_AUTH_JWT_USE_ISSUED_AT, // Y/N flag

    // OAuth2
    CONNECTOR_BASE_AUTH_OAUTH2_AUTHORIZATION_CODE,
    CONNECTOR_BASE_AUTH_OAUTH2_CLIENT_ID,
    CONNECTOR_BASE_AUTH_OAUTH2_CLIENT_SECRET,
    CONNECTOR_BASE_AUTH_OAUTH2_ENCODED_SECRET,
    CONNECTOR_BASE_AUTH_OAUTH2_PASSWORD,
    CONNECTOR_BASE_AUTH_OAUTH2_REDIRECT_URI,
    CONNECTOR_BASE_AUTH_OAUTH2_REFRESH_TOKEN,
    CONNECTOR_BASE_AUTH_OAUTH2_TOKEN_URL,
    CONNECTOR_BASE_AUTH_OAUTH2_USERNAME,

    // PEM private key loading
    CONNECTOR_BASE_AUTH_PEM_FILE,

    // PFX key store loading
    CONNECTOR_BASE_AUTH_PFX_FILE,
    CONNECTOR_BASE_AUTH_PFX_PASSWORD

}
